-   id: tsc
    name: typescript
    entry: tsc --noEmit
    language: node
    'types': [ts,tsx]
    args: []
    require_serial: false
    additional_dependencies: ["typescript@2.5.3-insiders.20170908"]
    minimum_pre_commit_version: '0'
