-   id: tsc
    name: typescript
    entry: tsc --noEmit
    language: node
    'types': [ts,tsx]
    args: []
    require_serial: true
    additional_dependencies: ["typescript@2.0.6-insiders.20161017"]
    minimum_pre_commit_version: '0'
