-   id: tsc
    name: typescript
    entry: tsc --noEmit
    language: node
    'types': [ts,tsx]
    args: []
    require_serial: true
    additional_dependencies: ["typescript@2.8.0-insiders.20180315"]
    minimum_pre_commit_version: '0'
