-   id: tsc
    name: typescript
    entry: tsc --noEmit
    language: node
    'types': [ts,tsx]
    args: []
    require_serial: true
    additional_dependencies: ["typescript@4.1.0-dev.20200906"]
    minimum_pre_commit_version: '0'
