-   id: tsc
    name: typescript
    description: ''
    entry: tsc --noEmit
    language: node
    'types': [ts,tsx]
    args: []
    require_serial: false
    additional_dependencies: ["typescript@4.9.0-dev.20220909"]
    minimum_pre_commit_version: '0'
