-   id: tsc
    name: typescript
    entry: tsc --noEmit
    language: node
    'types': [ts,tsx]
    args: []
    require_serial: true
    additional_dependencies: ["typescript@2.2.2-insiders.20170317"]
    minimum_pre_commit_version: '0'
