-   id: tsc
    name: typescript
    entry: tsc --noEmit
    language: node
    'types': [ts,tsx]
    args: []
    require_serial: true
    additional_dependencies: ["typescript@3.1.3-insiders.20181024"]
    minimum_pre_commit_version: '0'
