-   id: tsc
    name: typescript
    entry: tsc --noEmit
    language: node
    'types': [ts,tsx]
    args: []
    require_serial: false
    additional_dependencies: ["typescript@3.4.0-dev.20190221"]
    minimum_pre_commit_version: '0'
