-   id: tsc
    name: typescript
    entry: tsc --noEmit
    language: node
    'types': [ts,tsx]
    args: []
    require_serial: false
    additional_dependencies: ["typescript@4.4.1-rc"]
    minimum_pre_commit_version: '0'
