-   id: tsc
    name: typescript
    entry: tsc --noEmit
    language: node
    'types': [ts,tsx]
    args: []
    require_serial: true
    additional_dependencies: ["typescript@2.3.0-dev.20170412"]
    minimum_pre_commit_version: '0'
